if lspci -nn | grep "106b:180[12]" >/dev/null; then
  echo "Detected MacBook with T2 chip. Installing support items..."

  omarchy-pkg-add \
    linux-t2 \
    linux-t2-headers \
    apple-t2-audio-config \
    apple-bcm-firmware \
    t2fanrd

  systemctl enable t2fanrd.service

  mkdir -p /etc/modules-load.d
  {
    echo "t2bce_vhci"
    echo "hci_bcm4377"
  } > /etc/modules-load.d/t2.conf

  mkdir -p /etc/mkinitcpio.conf.d
  echo "MODULES+=(t2bce_vhci usbhid hid_apple hid_generic xhci_pci xhci_hcd)" > \
    /etc/mkinitcpio.conf.d/apple-t2.conf

  mkdir -p /etc/limine-entry-tool.d
  cat > /etc/limine-entry-tool.d/t2-mac.conf <<'EOF'
# Generated by Omarchy installer for T2 Mac support
KERNEL_CMDLINE[default]+=" intel_iommu=on iommu=pt pm_async=off mem_sleep_default=deep"
EOF

  cat > /etc/t2fand.conf <<'EOF'
[Fan1]
low_temp=55
high_temp=75
speed_curve=linear
always_full_speed=false

[Fan2]
low_temp=55
high_temp=75
speed_curve=linear
always_full_speed=false
EOF
fi
